default:
  PROJECT_NAME: "first_project"
  DATABASE_URL: "postgresql://VovaZhelezkov:VovaZhelezkov@localhost:5432/first_project"
  SENTRY_DSN:
  TG_BOT_TOKEN: "1420670014:AAHXieVUzSf9q5XAjjJSgjfqHFr_BKrobF4"
  HOST: "4fd21eaf7d9f.ngrok.io"
  ALLOWED_HOSTS:
    - 4fd21eaf7d9f.ngrok.io


  heroku: "1420670014:AAHXieVUzSf9q5XAjjJSgjfqHFr_BKrobF4"
